<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>DvOpenhomeOrgSubscriptionLongPoll1.net</AssemblyName>    

        <TargetFrameworks>net8.0</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(TargetFrameworks);net8.0-ios;net8.0-maccatalyst</TargetFrameworks>

        <EnableDefaultItems>False</EnableDefaultItems>
 
        <IntermediateOutputPath>../../obj</IntermediateOutputPath>

        <Platform>AnyCPU</Platform>

        <ApplicationId>uk.co.linn.ohNet.OpenhomeOrgSubscriptionLongPoll1</ApplicationId>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="DvOpenhomeOrgSubscriptionLongPoll1.cs" />

        <ProjectReference Include="../../ohNet.net.csproj"/>
    </ItemGroup>

</Project>

