<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>CpOpenhomeOrgSubscriptionLongPoll1.net</AssemblyName>    

        <TargetFrameworks>net8.0</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(TargetFrameworks);net8.0-ios;net8.0-maccatalyst</TargetFrameworks>

        <EnableDefaultItems>False</EnableDefaultItems>
 
        <!-- NOTE: This needs to be the same output path as the ohNet.net csproj as some versions of the .NET SDK can't handle nested projects -->
        <IntermediateOutputPath>../../obj</IntermediateOutputPath>

        <Platform>AnyCPU</Platform>

        <!-- Required for Mac Catalyst -->
        <ApplicationId>uk.co.linn.ohNet.OpenhomeOrgSubscriptionLongPoll1</ApplicationId>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="CpOpenhomeOrgSubscriptionLongPoll1.cs" />

        <ProjectReference Include="../../ohNet.net.csproj"/>
    </ItemGroup>

</Project>

